version: "3.8"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

  airflow-webserver:
    build: .
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env 
    environment: &airflow-common-env
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__FERNET_KEY: ccLfeIwgdRtCNu9qcBOAZdBQoHYGAuNGH0VEcGRycvA=
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: "Transvalores676+"
      PYTHONPATH: /opt/airflow
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      _PIP_ADDITIONAL_REQUIREMENTS: "-r /requirements.txt"
      # Mantiene los navegadores en tu carpeta include de la VPS
      PLAYWRIGHT_BROWSERS_PATH: /opt/airflow/include/playwright_browsers
    volumes:
      - ./dags:/opt/airflow/dags
      - ./output:/opt/airflow/output
      - ./include:/opt/airflow/include
      - ./requirements.txt:/requirements.txt
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:8083:8080"
    command: webserver

  airflow-scheduler:
    build: .
    restart: always
    depends_on:
      - airflow-webserver
    env_file:
      - .env 
    environment: *airflow-common-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
      - ./output:/opt/airflow/output
      - ./requirements.txt:/requirements.txt
      - /var/run/docker.sock:/var/run/docker.sock
    command: scheduler

  airflow-worker:
    build: .
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env 
    environment: *airflow-common-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
      - ./output:/opt/airflow/output
      - ./requirements.txt:/requirements.txt
      - /var/run/docker.sock:/var/run/docker.sock
    # Quitamos el comando de apt-get para evitar el bootloop
    command: celery worker

volumes:
  postgres_data: